### ISSUE TITLE
readme.md

### ISSUE THREAD

**Issue by ghost** [caroso1222/wapy#1]
Just a minor issue. Change 'product' to 'review' in below code:
```
#### PRODUCT REVIEWS ####
reviews = wapy.product_reviews('21853453')
for review in reviews:
    print (product.reviewer)
```

So correct one should be:
```
#### PRODUCT REVIEWS ####
reviews = wapy.product_reviews('21853453')
for review in reviews:
    print (review.reviewer)
```

**Comment by caroso1222** [comment]
You're right, thank you for noting this!

Would you like to open a PR and fix this issue? or should I work on it.

**Comment by patil16nit** [comment]
@caroso1222 I have updated README, Kindly check the [pull request](https://github.com/caroso1222/wapy/pull/2)

**Comment by caroso1222** [comment]
Thanks @patil16nit. It's merged now: https://github.com/caroso1222/wapy/pull/2.
